version: '2.2'
services:
#  app:
#    build:
#      context: ./docker
#      dockerfile: DockerfileAnsible
#    volumes:
#      - .:/app
#    command: 'tail -f /dev/null'
  redis:
    image: redis:5.0.3-alpine
    privileged: true
    ports:
      - "6379:6379"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    privileged: true
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    privileged: true
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml