version: '2.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: 'tail -f /dev/null'
    env_file:
      - .env
    devices:
      - /dev/video0:/dev/video0
  redis:
    image: redis:5.0.3-alpine
    hostname: redis
    privileged: true
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    hostname: elastic
    privileged: true
    ports:
      - "9200:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    volumes:
      - /tmp/log:/tmp/log/
      - ./resources/logstash:/usr/share/logstash/pipeline/
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    privileged: true
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml